export declare const typeOf: (value: any, what?: string) => any;
export declare const isObject: (value: any) => any;
export declare const getRef: (object: object, key: string) => any;
export declare const relay: (object: object, symbol: string, depth?: number, parent?: string, result?: {}, level?: number, cyclic?: Map<any, any>) => {};
export declare const charCount: (word: string, char?: string | RegExp) => number;
export declare const sizeOf: (object: Object) => number;
export declare const extend: (item: object[]) => {};
export declare const deflate: (obj: object, symbol?: string, parent?: string | object, res?: {}) => {};
export declare const dissolve: (list: Array<any>, depth?: number, level?: number) => any;
